<?php

namespace App\Support;

/**
 * Esquema de datos de Carmen WMS (réplica exacta del artifact).
 * dataset JS => tabla, clave natural y campos [claveJS, columna, tipo].
 * Generado a partir del modelo de datos del prototipo; no editar a mano sin
 * actualizar la migración 2026_09_23_000300_create_carmen_tables.
 */
final class CarmenSchema
{
    public const DATASETS = [
        'WAREHOUSES' => ['table' => 'cw_warehouses', 'key' => 'id', 'fields' => [
            ['id', 'code', 'string'],
            ['name', 'name', 'string'],
            ['short', 'short', 'string'],
            ['city', 'city', 'string'],
            ['bodegas', 'bodegas', 'json'],
            ['type', 'wh_type', 'string'],
        ]],
        'RACKS' => ['table' => 'cw_racks', 'key' => 'id', 'fields' => [
            ['id', 'code', 'string'],
            ['name', 'name', 'string'],
            ['filas', 'filas', 'integer'],
            ['cols', 'cols', 'integer'],
            ['zona', 'zona', 'string'],
            ['wh', 'wh', 'string'],
            ['tipo', 'tipo', 'string'],
            ['cap', 'cap', 'integer'],
        ]],
        'PRODUCTS' => ['table' => 'cw_products', 'key' => 'codigo', 'fields' => [
            ['codigo', 'codigo', 'string'],
            ['desc', 'descripcion', 'string'],
            ['um', 'um', 'string'],
            ['cat', 'cat', 'string'],
            ['sub', 'sub', 'string'],
            ['rot', 'rot', 'string'],
            ['min', 'min_qty', 'integer'],
            ['max', 'max_qty', 'integer'],
            ['vidaUtil', 'vida_util', 'integer'],
            ['precio', 'precio', 'float'],
            ['estado', 'estado', 'string'],
            ['fabrica', 'fabrica', 'string'],
            ['peso', 'peso', 'float'],
            ['serializado', 'serializado', 'boolean'],
        ]],
        'LOCATIONS' => ['table' => 'cw_locations', 'key' => 'id', 'fields' => [
            ['id', 'code', 'string'],
            ['rack', 'rack', 'string'],
            ['fila', 'fila', 'integer'],
            ['col', 'col', 'integer'],
            ['wh', 'wh', 'string'],
            ['cap', 'cap', 'integer'],
            ['sort', 'sort_seq', 'integer'],
            ['blocked', 'blocked', 'boolean'],
            ['tipo', 'tipo', 'string'],
        ]],
        'STOCK' => ['table' => 'cw_stock', 'key' => null, 'fields' => [
            ['loc', 'loc', 'string'],
            ['rack', 'rack', 'string'],
            ['wh', 'wh', 'string'],
            ['codigo', 'codigo', 'string'],
            ['lote', 'lote', 'string'],
            ['qty', 'qty', 'integer'],
            ['ingreso', 'ingreso', 'string'],
            ['venc', 'venc', 'string'],
            ['estado', 'estado', 'string'],
            ['reservado', 'reservado', 'integer'],
        ]],
        'CLIENTS' => ['table' => 'cw_clients', 'key' => 'codigo', 'fields' => [
            ['codigo', 'codigo', 'string'],
            ['nombre', 'nombre', 'string'],
            ['dpto', 'dpto', 'string'],
            ['ciudad', 'ciudad', 'string'],
            ['canal', 'canal', 'string'],
            ['tel', 'tel', 'string'],
            ['nit', 'nit', 'string'],
            ['estado', 'estado', 'string'],
            ['pedidos', 'pedidos', 'integer'],
            ['direccion', 'direccion', 'string'],
            ['zona', 'zona', 'string'],
        ]],
        'DRIVERS' => ['table' => 'cw_drivers', 'key' => 'ci', 'fields' => [
            ['ci', 'ci', 'string'],
            ['nombre', 'nombre', 'string'],
            ['lic', 'lic', 'string'],
            ['tel', 'tel', 'string'],
            ['estado', 'estado', 'string'],
            ['viajes', 'viajes', 'integer'],
        ]],
        'TRUCKS' => ['table' => 'cw_trucks', 'key' => 'placa', 'fields' => [
            ['placa', 'placa', 'string'],
            ['tipo', 'tipo', 'string'],
            ['marca', 'marca', 'string'],
            ['cap', 'cap', 'string'],
            ['estado', 'estado', 'string'],
            ['chofer', 'chofer', 'string'],
        ]],
        'USERS_DESK' => ['table' => 'cw_users_desk', 'key' => 'user', 'fields' => [
            ['user', 'username', 'string'],
            ['nombre', 'nombre', 'string'],
            ['rol', 'rol', 'string'],
            ['wh', 'wh', 'json'],
            ['estado', 'estado', 'string'],
            ['ult', 'ult', 'string'],
            ['correo', 'correo', 'string'],
        ]],
        'USERS_COL' => ['table' => 'cw_users_col', 'key' => 'user', 'fields' => [
            ['user', 'username', 'string'],
            ['nombre', 'nombre', 'string'],
            ['rol', 'rol', 'string'],
            ['wh', 'wh', 'string'],
            ['estado', 'estado', 'string'],
            ['device', 'device', 'string'],
            ['online', 'online', 'boolean'],
            ['documento', 'documento', 'string'],
        ]],
        'DEVICES' => ['table' => 'cw_devices', 'key' => 'id', 'fields' => [
            ['id', 'code', 'string'],
            ['modelo', 'modelo', 'string'],
            ['so', 'so', 'string'],
            ['bat', 'bat', 'integer'],
            ['app', 'app', 'string'],
            ['user', 'username', 'string'],
            ['wh', 'wh', 'string'],
            ['online', 'online', 'boolean'],
            ['cola', 'cola', 'integer'],
        ]],
        'INGRESOS' => ['table' => 'cw_ingresos', 'key' => 'nro', 'fields' => [
            ['nro', 'nro', 'string'],
            ['fecha', 'fecha', 'string'],
            ['tipo', 'tipo', 'string'],
            ['origen', 'origen', 'string'],
            ['estado', 'estado', 'string'],
            ['lines', 'lines', 'json'],
            ['doc', 'doc', 'string'],
            ['usuario', 'usuario', 'string'],
            ['muelle', 'muelle', 'string'],
            ['wh', 'wh', 'string'],
            ['obs', 'obs', 'string'],
        ]],
        'PEDIDOS' => ['table' => 'cw_pedidos', 'key' => 'nro', 'fields' => [
            ['nro', 'nro', 'string'],
            ['cliente', 'cliente', 'string'],
            ['fecha', 'fecha', 'string'],
            ['estado', 'estado', 'string'],
            ['lines', 'lines', 'json'],
            ['picker', 'picker', 'string'],
            ['prioridad', 'prioridad', 'string'],
            ['transporte', 'transporte', 'string'],
            ['bultos', 'bultos', 'integer'],
            ['ola', 'ola', 'string'],
            ['ref', 'ref', 'string'],
            ['wh', 'wh', 'string'],
            ['obs', 'obs', 'string'],
        ]],
        'DESPACHOS' => ['table' => 'cw_despachos', 'key' => 'nro', 'fields' => [
            ['nro', 'nro', 'string'],
            ['fecha', 'fecha', 'string'],
            ['placa', 'placa', 'string'],
            ['chofer', 'chofer', 'string'],
            ['pedidos', 'pedidos', 'json'],
            ['bultos', 'bultos', 'integer'],
            ['destino', 'destino', 'string'],
            ['estado', 'estado', 'string'],
            ['wh', 'wh', 'string'],
            ['salida', 'salida', 'string'],
        ]],
        'KARDEX' => ['table' => 'cw_kardex', 'key' => null, 'fields' => [
            ['ts', 'ts', 'string'],
            ['tipo', 'tipo', 'string'],
            ['dir', 'dir', 'string'],
            ['codigo', 'codigo', 'string'],
            ['lote', 'lote', 'string'],
            ['qty', 'qty', 'integer'],
            ['from', 'from_loc', 'string'],
            ['to', 'to_loc', 'string'],
            ['user', 'username', 'string'],
            ['doc', 'doc', 'string'],
            ['device', 'device', 'string'],
            ['offline', 'offline', 'boolean'],
            ['wh', 'wh', 'string'],
        ]],
        'CONTEOS' => ['table' => 'cw_conteos', 'key' => 'nro', 'fields' => [
            ['nro', 'nro', 'integer'],
            ['tipo', 'tipo', 'string'],
            ['wh', 'wh', 'string'],
            ['apertura', 'apertura', 'string'],
            ['estado', 'estado', 'string'],
            ['ubic', 'ubic', 'integer'],
            ['contadas', 'contadas', 'integer'],
            ['dif', 'dif', 'integer'],
            ['resp', 'resp', 'string'],
            ['ira', 'ira', 'float'],
            ['lines', 'lines', 'json'],
            ['alcance', 'alcance', 'string'],
            ['modalidad', 'modalidad', 'string'],
            ['bloquear', 'bloquear', 'boolean'],
        ]],
        'IMPORT_HISTORY' => ['table' => 'cw_import_history', 'key' => null, 'fields' => [
            ['fecha', 'fecha', 'string'],
            ['dataset', 'dataset', 'string'],
            ['archivo', 'archivo', 'string'],
            ['filas', 'filas', 'integer'],
            ['ok', 'ok_rows', 'integer'],
            ['err', 'err_rows', 'integer'],
            ['user', 'username', 'string'],
        ]],
        'ALERTS' => ['table' => 'cw_alerts', 'key' => null, 'fields' => [
            ['k', 'kind', 'string'],
            ['t', 'title', 'string'],
            ['s', 'subtitle', 'string'],
        ]],
        'AJUSTES' => ['table' => 'cw_ajustes', 'key' => 'nro', 'fields' => [
            ['nro', 'nro', 'string'],
            ['fecha', 'fecha', 'string'],
            ['wh', 'wh', 'string'],
            ['loc', 'loc', 'string'],
            ['codigo', 'codigo', 'string'],
            ['lote', 'lote', 'string'],
            ['tipo', 'tipo', 'string'],
            ['qty', 'qty', 'integer'],
            ['motivo', 'motivo', 'string'],
            ['obs', 'obs', 'string'],
            ['user', 'username', 'string'],
            ['estado', 'estado', 'string'],
            ['aprobador', 'aprobador', 'string'],
            ['doc', 'doc', 'string'],
        ]],
        'SETTINGS' => ['table' => 'cw_settings', 'key' => 'k', 'fields' => [
            ['k', 'k', 'string'],
            ['v', 'v', 'json'],
        ]],
        'LABELS' => ['table' => 'cw_labels', 'key' => 'tpl', 'fields' => [
            ['tpl', 'tpl', 'string'],
            ['cfg', 'cfg', 'json'],
            ['version', 'version', 'integer'],
        ]],
    ];
}
